# Generated by Django 5.0.7 on 2024-08-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTrack', '0006_alter_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
