# Generated by Django 5.0.7 on 2024-08-06 20:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTrack', '0008_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
