# Generated by Django 5.0.7 on 2024-08-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTrack', '0011_checkin_donetoday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='doneToday',
            field=models.DateField(),
        ),
    ]
